### PR TITLE
prep-time for lunch

### PR DESCRIPTION
**Pull request by minku1016**
fried rice the winning recipe!!

## 🎯 Objective

Updating the prep time

## 🛠️ Changes made
Updating it to give a good estimated time required for cooking

### CODE REVIEW

**Comment by nbretschneider** [comment]
Great estimation on the prep time!

**Comment by ShotaroIshizuka** [comment]
Approved! 💯

**Comment by ShotaroIshizuka** [comment]
Conflict

**Comment by odellsj** [comment]
@minku1016 please submit another pull request for prep time for lunch

**Pull request closed without merging**
