### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by nbretschneider**
What about doing 4 servings?

## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by minku1016 — APPROVED** [review]
4 serving makes sense, although we have 5 people. One doesn't like breakfast burritos unfortunately.

**Comment by minku1016** [comment]
@ShotaroIshizuka can you please give a second approval?

**Comment by ShotaroIshizuka** [comment]
Ideally we want to be more inclusive...is there any way to achieve inclusion?

**Comment by ShotaroIshizuka** [comment]
After discussing with you it now makes sense to me. One doesn't like burritos, and we shouldn't force it. Approved ! 💯

**Pull request merged**
